version: '3.9'

services:
    scylla:
        image: tonuser/scylla-bdd:1.0
        ports:
            - "9045:9042"
        volumes:
            - scylla-data:/var/lib/scylla
        networks:
            - backend

    spring-app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - scylla
        environment:
        - SPRING_CASSANDRA_CONTACT-POINTS=scylla
        - SPRING_CASSANDRA_PORT=9045
        - SPRING_CASSANDRA_KEYSPACE-NAME=rental
        - SPRING_CASSANDRA_USERNAME=cassandra
        - SPRING_CASSANDRA_PASSWORD=cassandra
        - SPRING_CASSANDRA_LOCAL-DATACENTER=datacenter1
        networks:
            - backend

volumes:
    scylla-data:

networks:
    backend:
